spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_rest?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always

